# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'


- script: |
    npm init --yes
    npm install
    npm install -g protractor
    webdriver-manager update
    webdriver-manager start

-task: RunScripts@1
  inputs:
  Tool: Node
  Arguments : ./protractor.conf.js
  Working Folder: ./


- script: |
    protractor conf.js
