# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'


- script: |
    npm init --yes
    npm install
    npm install -g protractor
    webdriver-manager update
    webdriver-manager start
  displayName: 'Command Line Script'

- script: 'protractor conf.js'
  displayName: runTest

- task: PowerShell@1
  displayName: 'PowerShell Script'
  inputs:
    scriptType: inlineScript

    inlineScript: |
     $date=$(Get-Date).ToUniversalTime().ToString(‘d-M-yyyy-HH’);
     Write-Host “##vso[task.setvariable variable=time]$date”


- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
